### ISSUE TITLE
ImapClient: javax.mail.FolderClosedException

### ISSUE THREAD

**Issue by r0hi7** [r0hi7/TeleDot#2]
Since the schedular is used to connect to the Imap IDLE server, and the entire implementation of server ImapClient in in multithread mode with restart rate set to 120000, which is causing this exception .
```
javax.mail.FolderClosedException
	at com.sun.mail.imap.IMAPMessage.getProtocol(IMAPMessage.java:145)
	at com.sun.mail.imap.IMAPMessage.loadBODYSTRUCTURE(IMAPMessage.java:1279)
	at com.sun.mail.imap.IMAPMessage.getContentType(IMAPMessage.java:450)
	at javax.mail.internet.MimeBodyPart.isMimeType(MimeBodyPart.java:1050)
	at javax.mail.internet.MimeMessage.isMimeType(MimeMessage.java:985)
	at io.github.teledot.utils.MailParser.getTextFromMessage(MailParser.java:53)
	at io.github.teledot.utils.MailParser.<init>(MailParser.java:29)
	at io.github.teledot.Telegram.ForwardMailsToTelegram.sendToTelegram(ForwardMailsToTelegram.java:28)
	at io.github.teledot.EmailInteraction.ImapClient$1.messagesAdded(ImapClient.java:81)
	at javax.mail.event.MessageCountEvent.dispatch(MessageCountEvent.java:150)
	at javax.mail.EventQueue.run(EventQueue.java:134)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by r0hi7** [comment]
Ever after f69b849, the ImapClient is failing with `FolderClosedException`. Entire trace:

```
javax.mail.FolderClosedException
	at com.sun.mail.imap.IMAPMessage.getProtocol(IMAPMessage.java:145)
	at com.sun.mail.imap.IMAPMessage.loadBODYSTRUCTURE(IMAPMessage.java:1279)
	at com.sun.mail.imap.IMAPMessage.getContentType(IMAPMessage.java:450)
	at javax.mail.internet.MimeBodyPart.isMimeType(MimeBodyPart.java:1050)
	at javax.mail.internet.MimeMessage.isMimeType(MimeMessage.java:985)
	at io.github.teledot.utils.MailParser.getTextFromMessage(MailParser.java:53)
	at io.github.teledot.utils.MailParser.<init>(MailParser.java:29)
	at io.github.teledot.Telegram.ForwardMailsToTelegram.sendToTelegram(ForwardMailsToTelegram.java:28)
	at io.github.teledot.EmailInteraction.ImapClient$1.messagesAdded(ImapClient.java:81)
	at javax.mail.event.MessageCountEvent.dispatch(MessageCountEvent.java:150)
	at javax.mail.EventQueue.run(EventQueue.java:134)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
The main reason for this might be the long IDLE settings with the thread.

**Comment by r0hi7** [comment]
This exception is thrown when a method is invoked on a Messaging object and the Folder that owns that object has died due to some reason. So I need to process the message object before the folder for that object is closed.
